<br>
<div class="description">
    <h1>Ты входишь в команту которая была слева от первой <br></h1>
    <p>В комнате так же пусто. Из кмнаты ведет проход направо.
</div>

<div class="choises">
    <form>
        <input class="choise" type="button" value="Правая комната" onClick='location.href="/there"'>
        <input class="choise" type="button" value="Первая комната" onClick='location.href="/first"'>
    </form>
</div>
