<br>
<div class="description">
    <h2>Ты входишь в команту которая была слева от первой <br></h2>
    <p class="text-center">В комнате так же пусто. Из кмнаты ведет проход направо.
</div>

<div class="choises">
    <form>
        <a class="btn btn-primary btn-lg btn-block" href="/there" role="button">Правая комната</a>
        <a class="btn btn-primary btn-lg btn-block" href="/first" role="button">Первая комната</a>
    </form>
</div>
