<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="/css/style.css" type="text/css" />
    <link rel="stylesheet" href="/css/bootstrap.css" type="text/css" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>DCTame</title>
</head>
<body>
<!-- Header -->
<div class="container">
    <div class="row">
        <div class="col-md-12 upper">

        </div>
    </div>
</div>
<!-- End Header -->
<!-- Content -->
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-2">
            <div id="wrapper">
                %%__page__%%
            </div>
        </div>
    </div>
</div>
<!-- End Content -->
<!-- Footer -->
<div class="container-fluid">
    <div class="row">
        <div id="footer">
            <div id="wrapper">

            </div>
        </div>
    </div>
</div>
<!-- End Footer -->

<!-- jQuery first, then Bootstrap JS. -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>

</body>
</html>


