<!DOCTYPE html>
<html lang="en-US" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link rel="stylesheet" href="/css/style.css" type="text/css" />
<head>
    <title>DCTame</title>
</head>
<body>
<!-- Header -->
<div id="header">
    <input class="choise" type="button" value="главная" onClick='location.href="/"'>
  </div>
  <!-- End Header -->
<!-- Content -->
<div id="content">
    <div id="wrapper">
   %%__page__%%
    </div>
</div>

<!-- End Content -->
<!-- Footer -->
<div id="footer">
    <div id="wrapper">
    </div>
</div>
<!-- End Footer -->
</body>
</html>


