<br>
<div class="description">
    <h1>Ты входишь в команту которая была справа от первой <br></h1>
    <p>В комнате так же пусто. Из кмнаты ведет проход Налево.
</div>
<div class="choises">
    <form>
        <input class="choise" type="button" value="Левая комната" onClick='location.href="/here"'>
        <input class="choise" type="button" value="Первая комната" onClick='location.href="/first"'>
    </form>
</div>
