<br>
<div class="description">
    <h2>Ты входишь в команту которая была справа от первой <br></h2>
    <p class="text-center" >В комнате на полу лежит монетка. Из комнаты ведет проход Налево.
</div>
<div class="choises">
    <form>
        <a class="btn btn-primary btn-lg btn-block" href="/here" role="button">Левая комната</a>
        <a class="btn btn-primary btn-lg btn-block" href="/first" role="button">Первая комната</a>
        <br>
        <button type="button" class="btn btn-primary">Взять монетку</button>


        <script>
            $(document).ready(function(){                          // по завершению загрузки страницы
                $('#example-3').click(function(){                  // вешаем на клик по элементу с id = example-3
                    $.post('ajax/example.xml', {}, function(xml){  // загрузку XML из файла example.xml
                        $('#example-3').html('');
                        $(xml).find('note').each(function(){       // заполняем DOM элемент данными из XML
                            $('#example-3').append('To: '   + $(this).find('to').text() + '<br/>')
                                .append('From: ' + $(this).find('from').text() + '<br/>')
                                .append('<b>'    + $(this).find('heading').text() + '</b><br/>')
                                .append(           $(this).find('body').text() + '<br/>');
                        });
                    }, 'xml');                                     // указываем явно тип данных
                })
            });
        </script>
    </form>
</div>
